version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 taxi.wsgi --workers=4
    volumes:
      - .:/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: kartoza/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

volumes:
  postgres_data: